version: '3'

networks:
  pg:
    driver: bridge

services:
  pg:
    container_name: pg_go
    image: postgres
    environment:
      - POSTGRES_USER='postgres'
      - POSTGRES_PASSWORD='postgres'
    restart: always
    ports:
      - 5432:5432
    networks:
      - pg
